### ISSUE TITLE
.gui.xml problem

### ISSUE THREAD

**Issue by thisischrys** [totemo/watson_macros#1]
I downloaded the .gui.xml and .macros.txt files.
I don't have a minecraft/mods/macros/ folder however: my macros files are at liteconfig\common\macros (by default using the latest version)

However hitting tilda I just get the regular screen: http://i.imgur.com/VGorewj.png
Watson itself works, the keybindings work. 
What am I missing?

**Comment by totemo** [comment]
Are you on 1.7.10?

Have you installed LiteLoader and Macro/Keybind, per the instructions at https://github.com/totemo/watson_macros/releases ?

What files do you have in liteconfig\common\macros\ ? 

Those files certainly work in that folder.  It may be that Macro/Keybind has relocated its default location for that stuff and is picking up the .gui.xml and .macros.txt files from the other location for the sake of backwards compatibility with older versions of Macro/Keybind.

Please double-check your Macro/Keybind mod install, since that should do something when you press backquote/tilde, irrespective of whether watson_macros is working.

Also, try making the folders to produce the .minecraft\mods\macros\ directory structure and place .gui.xml and .macros.txt in there.

**Comment by thisischrys** [comment]
cauldron is dead
